platform :ios, '8.0'

# Facebook SDK and Parse SDK
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'Parse'
pod 'ParseFacebookUtilsV4'

# Google Analytics SDK
pod 'Google/Analytics', '~> 1.0.0'

# Firebase SDK
pod 'Firebase', '>= 2.3.1'

# Web Service
pod 'AFNetworking', '~> 2.0'

# Progress Indicator
pod 'MRProgress'

# Messaging UI
pod 'JSQMessagesViewController'
pod 'IDMPhotoBrowser'
pod 'RNGridMenu', '~> 0.1.2'
pod 'SDWebImage', '~>3.7'

# Image Editor
pod 'CLImageEditor'
pod 'RSKImageCropper'

# Alternative for default UI
pod 'JTImageButton'
pod 'APNumberPad'
pod 'SZTextView'
pod 'MMPickerView', '~> 0.0.1'

